-- 004_lily_questions_expansion.sql — curated_v2, 200 rows (160 general + 40 adult-flagged).
-- Matches the LIVE production lily_questions schema (canonical_answer text,
-- acceptable_answers text[]), which drifted from migration 001 (answer/jsonb) —
-- the table was created out-of-band before 001 ran. Applied to production 2026-07-14.

-- Lily curated question bank expansion — curated_v2 — 200 rows (160 general + 40 adult)
-- Columns: (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source)
-- lily_questions expansion — curated_v2 — GENERAL / academic (40)
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Paris grew up on the banks of this famous French river.', 'the Seine', ARRAY['seine', 'the seine', 'sen', 'sane', 'the sen']::text[], 1, 'The Seine — Paris''s original main street.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'At sea level, plain water freezes at exactly this many degrees Celsius.', '0', ARRAY['0', 'zero', 'zero degrees', '0 degrees', 'zero celsius']::text[], 1, 'Zero — water''s big round off switch.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Thanks to soft ground and stubborn luck, a famously tilted bell tower leans over this small Italian city.', 'Pisa', ARRAY['pisa', 'piza', 'peesa', 'pizza']::text[], 1, 'Pisa — eight centuries of leaning and still standing.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Built over centuries to keep out invaders, the Great Wall winds across this vast Asian country.', 'China', ARRAY['china']::text[], 1, 'China — the wall took longer to build than most empires lasted.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Most of the Amazon rainforest sits inside this huge South American country.', 'Brazil', ARRAY['brazil', 'brasil']::text[], 1, 'Brazil — the rainforest takes up more of the map than the beaches do.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Working an entire summer to fill a single jar, honey is made by these buzzing striped insects.', 'bees', ARRAY['bees', 'bee', 'honeybees', 'honey bees', 'honeybee', 'the bees']::text[], 1, 'Bees — a whole summer of overtime for one jar.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Plants turn sunlight, water, and carbon dioxide into food through this leafy green process.', 'photosynthesis', ARRAY['photosynthesis', 'photo synthesis', 'photosynthesys']::text[], 1, 'Photosynthesis — plants have been solar-powered all along.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Legend says a falling apple sparked the theory of gravity for this English scientist.', 'Isaac Newton', ARRAY['newton', 'isaac newton', 'sir isaac newton']::text[], 1, 'Newton — one bruised apple, one changed universe.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'The Greeks finally cracked Troy by hiding soldiers inside a giant wooden version of this animal.', 'horse', ARRAY['horse', 'a horse', 'the horse', 'wooden horse', 'trojan horse']::text[], 1, 'A horse — history''s most successful unwanted gift.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'E equals m c squared was the signature work of this wild-haired German-born physicist.', 'Albert Einstein', ARRAY['einstein', 'albert einstein', 'einstien']::text[], 1, 'Einstein — proof that a bad hair day can still be a good science day.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'The Great Barrier Reef stretches along the northeast coast of this sun-baked southern country.', 'Australia', ARRAY['australia', 'austraila']::text[], 1, 'Australia — the only landmark you can see from space and snorkel through.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Flowing north out of Africa, the Nile finally empties into this busy sea.', 'the Mediterranean', ARRAY['mediterranean', 'the mediterranean', 'mediterranean sea', 'the mediterranean sea']::text[], 2, 'The Mediterranean — the Nile''s long trip ends at the world''s busiest swimming pool.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Table salt is one part sodium and one part this sharp-smelling greenish-gas element.', 'chlorine', ARRAY['chlorine', 'clorine', 'chloreen']::text[], 2, 'Chlorine — poison gas plus explosive metal equals dinner seasoning. Chemistry is wild.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Genghis Khan stitched together history''s largest land empire, known by this name.', 'the Mongol Empire', ARRAY['mongol', 'mongol empire', 'the mongol empire', 'mongolian empire', 'mongols', 'the mongols', 'mongolian']::text[], 2, 'The Mongol Empire — one man, one horse, most of a continent.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'The Nobel Prizes are bankrolled by the fortune Alfred Nobel made inventing this explosive.', 'dynamite', ARRAY['dynamite', 'dinamite']::text[], 2, 'Dynamite — he blew things up, then funded the peace prize. Balance.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Two atria on top, two ventricles below — the human heart has exactly this many chambers.', 'four', ARRAY['4', 'four']::text[], 2, 'Four — a two-bedroom, two-bath arrangement, always occupied.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'The stormy strait at South America''s southern tip is named for this Portuguese explorer.', 'Magellan', ARRAY['magellan', 'ferdinand magellan', 'magellen', 'magelan']::text[], 2, 'Magellan — the strait kept his name even though the trip didn''t keep him.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'In Mumbai or Delhi, dinner gets paid for in this Indian currency.', 'rupee', ARRAY['rupee', 'rupees', 'the rupee', 'roopee']::text[], 2, 'The rupee — over a billion wallets can''t be wrong.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'DNA''s famous twisted-ladder shape goes by this two-word geometric name.', 'double helix', ARRAY['double helix', 'a double helix', 'the double helix', 'double helux']::text[], 2, 'Double helix — the blueprint of you, shaped like a spiral staircase.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Melt copper together with tin and you get this age-naming ancient alloy.', 'bronze', ARRAY['bronze', 'brons']::text[], 2, 'Bronze — good enough to name an entire age after.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Stretching coast to coast across North Africa, the world''s largest hot desert is this one.', 'the Sahara', ARRAY['sahara', 'the sahara', 'sahara desert', 'the sahara desert']::text[], 2, 'The Sahara — roughly the size of the United States, with worse parking.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Mount Rushmore''s four stone presidents gaze out over this midwestern US state.', 'South Dakota', ARRAY['south dakota', 'south dekota']::text[], 2, 'South Dakota — four presidents, zero blinking.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Marie Curie won Nobel Prizes in physics and chemistry for pioneering the study of this glowing phenomenon.', 'radioactivity', ARRAY['radioactivity', 'radiation', 'radio activity']::text[], 2, 'Radioactivity — she named it, she tamed it, her notebooks still tick.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Erik the Red slapped a misleadingly lush name on this giant icy island.', 'Greenland', ARRAY['greenland', 'green land']::text[], 2, 'Greenland — history''s first real-estate marketing scam.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'He spent four years on his back painting the Sistine Chapel ceiling — name this Italian master.', 'Michelangelo', ARRAY['michelangelo', 'michael angelo', 'michelanjelo']::text[], 2, 'Michelangelo — four years of neck pain, five centuries of applause.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'The attack on Pearl Harbor pulled America into World War Two in this year.', '1941', ARRAY['1941', 'nineteen forty one', 'nineteen forty-one', 'forty one', '41']::text[], 2, 'Nineteen forty-one — December seventh, the date that lives in infamy.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Your pancreas keeps blood sugar in line by producing this vital hormone.', 'insulin', ARRAY['insulin', 'insuline']::text[], 2, 'Insulin — the pancreas''s one-word claim to fame.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Four score and seven years ago — the Gettysburg Address was delivered by this tall president.', 'Abraham Lincoln', ARRAY['lincoln', 'abraham lincoln', 'abe lincoln', 'abe']::text[], 2, 'Lincoln — two minutes of speech, one permanent spot in history.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'His hundred-day comeback tour ended at Waterloo in 1815 — name this exiled French emperor.', 'Napoleon', ARRAY['napoleon', 'napoleon bonaparte', 'bonaparte']::text[], 2, 'Napoleon — the comeback tour got cancelled permanently.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'King John sealed the Magna Carta at Runnymede in this early thirteenth-century year.', '1215', ARRAY['1215', 'twelve fifteen', 'twelve fifteen ad']::text[], 3, 'Twelve fifteen — the day kings learned about paperwork.', false, 'curated_v2');
-- two-step
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'He wrote The Magic Flute and left his Requiem unfinished — Mozart was born in this Austrian city.', 'Salzburg', ARRAY['salzburg', 'saltzburg', 'salsburg', 'salzberg']::text[], 3, 'Salzburg — the city still runs on Mozart and pastry.', false, 'curated_v2');
-- two-step
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'It carried Charles Darwin to the Galapagos — name this famously dog-named British survey ship.', 'HMS Beagle', ARRAY['beagle', 'the beagle', 'hms beagle']::text[], 3, 'The Beagle — a dog''s name on the ship that changed biology.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Gregor Mendel worked out the rules of heredity by crossbreeding these humble garden plants.', 'peas', ARRAY['peas', 'pea plants', 'pea', 'the pea', 'sweet peas']::text[], 3, 'Peas — genetics was invented in a monastery vegetable patch.', false, 'curated_v2');
-- two-step
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'It is not Auckland — windier and further south, New Zealand''s capital is this harbor city.', 'Wellington', ARRAY['wellington', 'welington']::text[], 3, 'Wellington — Auckland gets the flights, Wellington gets the government.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'One of the seven ancient wonders, the great Pharos lighthouse stood at this Egyptian port city.', 'Alexandria', ARRAY['alexandria', 'alexandrea']::text[], 3, 'Alexandria — the lighthouse fell, the library burned, the name survived everything.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Britain and China went to war in the 1840s over Britain''s illegal trade in this addictive drug.', 'opium', ARRAY['opium', 'opiym', 'opeum']::text[], 3, 'Opium — an actual war over an actual drug deal.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Nearly four-fifths of the air you are breathing right now is this unsung gas.', 'nitrogen', ARRAY['nitrogen', 'nitrogin']::text[], 3, 'Nitrogen — oxygen gets the credit, nitrogen does the volume.', false, 'curated_v2');
-- two-step
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Its island causeways crossed Lake Texcoco — beneath modern Mexico City lie the ruins of this Aztec capital.', 'Tenochtitlan', ARRAY['tenochtitlan', 'tenochtitlán', 'tenoch titlan', 'tenochtitlan city']::text[], 3, 'Tenochtitlan — a floating city, paved over into a megacity.', false, 'curated_v2');
-- closest-number
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Closest guess wins — the number of elements on the modern periodic table.', '118', ARRAY['118', 'one hundred eighteen', 'one hundred and eighteen', 'a hundred and eighteen', 'one eighteen']::text[], 3, 'One eighteen — and the last few only exist for milliseconds. They still count.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('academic', 'Cleopatra allied with Julius Caesar, then fell for this doomed Roman general.', 'Mark Antony', ARRAY['mark antony', 'antony', 'marc antony', 'anthony', 'mark anthony', 'marc anthony']::text[], 3, 'Mark Antony — history''s most expensive workplace romance.', false, 'curated_v2');
-- GENERAL / pop_culture (40)
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Harry Potter learns his spells at this famous school of witchcraft and wizardry.', 'Hogwarts', ARRAY['hogwarts', 'hogwards', 'hog warts']::text[], 1, 'Hogwarts — terrible safety record, unbeatable school spirit.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Mickey Mouse first whistled onto movie screens thanks to this pioneering animator.', 'Walt Disney', ARRAY['disney', 'walt disney']::text[], 1, 'Walt Disney — it all started with a mouse. His words.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Elsa belts out Let It Go in this blockbuster icy Disney musical.', 'Frozen', ARRAY['frozen']::text[], 1, 'Frozen — the song every parent still hears in their sleep.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Lightsabers, the Force, and a princess named Leia all come from this epic space franchise.', 'Star Wars', ARRAY['star wars', 'starwars']::text[], 1, 'Star Wars — a long time ago, in a galaxy that prints money.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'The Beatles played their first gigs in this northern English port city.', 'Liverpool', ARRAY['liverpool', 'liver pool']::text[], 1, 'Liverpool — four lads, one cavern, the whole world after.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'A giant great white shark terrorizes a beach town in this 1975 Spielberg blockbuster.', 'Jaws', ARRAY['jaws', 'jaw']::text[], 1, 'Jaws — two notes of music emptied every beach in America.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'SpongeBob flips Krabby Patties in this underwater fictional town.', 'Bikini Bottom', ARRAY['bikini bottom', 'bikini bottoms']::text[], 1, 'Bikini Bottom — the happiest commute under the sea.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Homer, Marge, and the kids live at 742 Evergreen Terrace in this cartoon town.', 'Springfield', ARRAY['springfield', 'spring field']::text[], 1, 'Springfield — in a state they will never, ever reveal.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Superman was rocketed to Earth as a baby from this doomed home planet.', 'Krypton', ARRAY['krypton', 'crypton', 'kripton']::text[], 1, 'Krypton — the only real estate crash that created a superhero.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Elvis Presley held court at this famously named Memphis mansion.', 'Graceland', ARRAY['graceland', 'grace land']::text[], 1, 'Graceland — the King''s castle, jungle room included.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'In The Wizard of Oz, Dorothy carries this little dog in her basket.', 'Toto', ARRAY['toto', 'todo']::text[], 1, 'Toto — small dog, enormous plot responsibilities.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'John Travolta and Samuel L. Jackson debate the Royale with Cheese in this 1994 Tarantino classic.', 'Pulp Fiction', ARRAY['pulp fiction', 'pulpfiction']::text[], 2, 'Pulp Fiction — the metric system''s finest hour in cinema.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'The Friends gang permanently occupies the orange couch at this punnily named coffee shop.', 'Central Perk', ARRAY['central perk', 'central park']::text[], 2, 'Central Perk — six people, one couch, zero coffee refills paid for.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Michael Jackson''s 1982 record is still the best-selling album of all time — name this spooky one-word title.', 'Thriller', ARRAY['thriller', 'thriler']::text[], 2, 'Thriller — forty years on, the zombie dance still slaps.', false, 'curated_v2');
-- two-step
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'First Vito, then Michael — The Godfather''s ruling family carries this surname.', 'Corleone', ARRAY['corleone', 'corleones', 'the corleones', 'corlioni', 'corleoni']::text[], 2, 'Corleone — the family business was never really olive oil.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'William Shatner captained the Enterprise in the original Star Trek as this captain.', 'Kirk', ARRAY['kirk', 'captain kirk', 'james kirk', 'james t kirk', 'james tiberius kirk']::text[], 2, 'Kirk — boldly going, dramatically pausing.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Smells Like Teen Spirit was howled into history by this Nirvana frontman.', 'Kurt Cobain', ARRAY['cobain', 'kurt cobain', 'curt cobain', 'kobain', 'kurt']::text[], 2, 'Kurt Cobain — one riff, and the eighties were officially over.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'The Lion King''s throne gets stolen by this jealous scheming uncle.', 'Scar', ARRAY['scar', 'scarr']::text[], 2, 'Scar — the uncle who put the drama in pride.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Rocky Balboa trains by running up the art museum steps in this American city.', 'Philadelphia', ARRAY['philadelphia', 'philly', 'filadelfia']::text[], 2, 'Philadelphia — the steps are now more famous than the museum.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Winter is Coming are the grim family words of this northern Game of Thrones house.', 'Stark', ARRAY['stark', 'house stark', 'the starks', 'starks']::text[], 2, 'Stark — they warned everyone, and nobody listened.', false, 'curated_v2');
-- two-step
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Will Smith''s nineties sitcom character left West Philadelphia for this posh Los Angeles neighborhood.', 'Bel-Air', ARRAY['bel air', 'bel-air', 'belair', 'bell air', 'bellaire']::text[], 2, 'Bel-Air — one little fight, one whole new zip code.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Amy Winehouse said no, no, no in this Grammy-winning one-word hit.', 'Rehab', ARRAY['rehab', 're hab', 'rihab']::text[], 2, 'Rehab — three nos, five Grammys.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Indiana Jones can face anything except these slithering reptiles.', 'snakes', ARRAY['snakes', 'snake', 'a snake']::text[], 2, 'Snakes — why did it have to be snakes.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'The Hunger Games'' bow-wielding heroine goes by this first name.', 'Katniss', ARRAY['katniss', 'katniss everdeen', 'catnis', 'catniss', 'cat nis']::text[], 2, 'Katniss — the girl on fire, named after a pond plant.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Tom Hanks shares chocolates and life advice from a bus bench in this 1994 film.', 'Forrest Gump', ARRAY['forrest gump', 'forest gump', 'gump', 'forrest']::text[], 2, 'Forrest Gump — run, answer, run.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Harry Styles first found fame in this X Factor boy band.', 'One Direction', ARRAY['one direction', '1 direction', 'one d', '1d', 'wandirection']::text[], 2, 'One Direction — five lads who went in about six directions.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Stranger Things'' monsters crawl out of this shadowy alternate dimension.', 'the Upside Down', ARRAY['upside down', 'the upside down', 'upsidedown']::text[], 2, 'The Upside Down — same Hawkins, much worse lighting.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Bob Marley carried reggae to the whole world from this Caribbean island nation.', 'Jamaica', ARRAY['jamaica', 'jamaika']::text[], 2, 'Jamaica — one island, one love, one unmistakable sound.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'The Office''s Scranton crew sells paper for this oddly named company.', 'Dunder Mifflin', ARRAY['dunder mifflin', 'dundermifflin', 'dunder miflin', 'dunder mufflin']::text[], 2, 'Dunder Mifflin — limitless paper, in a paperless world.', false, 'curated_v2');
-- two-step
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'A stolen envelope of cash, the Bates Motel, and one infamous shower — name this 1960 Hitchcock thriller.', 'Psycho', ARRAY['psycho', 'psyco', 'sycho']::text[], 3, 'Psycho — sixty years later, people still check behind the curtain.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'David Bowie played a flame-haired alien rock star under this glittering alter ego.', 'Ziggy Stardust', ARRAY['ziggy stardust', 'ziggy', 'ziggy star dust']::text[], 3, 'Ziggy Stardust — Bowie invented a rock star, then had to retire him onstage.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Meryl Streep''s icy magazine editor Miranda Priestly rules the fashion world in this 2006 film.', 'The Devil Wears Prada', ARRAY['the devil wears prada', 'devil wears prada']::text[], 3, 'The Devil Wears Prada — that''s all.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Tony Soprano ran his crew from the strip malls and diners of this US state.', 'New Jersey', ARRAY['new jersey', 'jersey', 'new jersy']::text[], 3, 'New Jersey — the Garden State, plus certain undisclosed businesses.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'The helmeted electronic duo Daft Punk came from this European country.', 'France', ARRAY['france', 'french']::text[], 3, 'France — the robots were French all along.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'The Dude in The Big Lebowski stays loyal to this creamy vodka-and-coffee-liqueur cocktail.', 'White Russian', ARRAY['white russian', 'a white russian', 'white russians']::text[], 3, 'The White Russian — it really ties the drink menu together.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Rick''s cafe, letters of transit, and here''s looking at you, kid — Casablanca is set in this North African country.', 'Morocco', ARRAY['morocco', 'marocco', 'morroco']::text[], 3, 'Morocco — though the whole thing was filmed in Burbank.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Prince recorded Purple Rain and never really left this Midwestern home city.', 'Minneapolis', ARRAY['minneapolis', 'minneapolis minnesota', 'mineapolis']::text[], 3, 'Minneapolis — the coldest city ever to sound that funky.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Parasite, the first non-English-language Best Picture winner, came from this Asian country.', 'South Korea', ARRAY['south korea', 'korea']::text[], 3, 'South Korea — one Oscar night, and subtitles stopped being scary.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Sherlock Holmes keeps his rooms at 221B on this London street.', 'Baker Street', ARRAY['baker street', 'baker', 'bakers street']::text[], 3, 'Baker Street — the most famous address that never existed.', false, 'curated_v2');
-- two-step
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('pop_culture', 'Jack Nicholson, an axe, and the line here''s Johnny — name this 1980 Kubrick horror film.', 'The Shining', ARRAY['the shining', 'shining']::text[], 3, 'The Shining — all work and no play, and you know the rest.', false, 'curated_v2');
-- GENERAL / wordplay (40)
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'You sleep in one every night, and a river flows along one — name this restful little word.', 'bed', ARRAY['bed', 'a bed', 'the bed']::text[], 1, 'Bed — rivers need their rest too.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'Put it after snow, gentle, and business and you get three very different fellows — name this short word.', 'man', ARRAY['man', 'a man', 'men']::text[], 1, 'Man — one word, three completely different wardrobes.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'It comes right after seven, and it sounds exactly like the past tense of eat — name this edible-sounding number.', 'eight', ARRAY['eight', '8', 'ate']::text[], 1, 'Eight — the only number you can have for dinner.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'One hangs upside down in caves, the other swings at baseballs — name this double-duty word.', 'bat', ARRAY['bat', 'a bat', 'bats']::text[], 1, 'Bat — same word, very different night jobs.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'It''s slang for one dollar and the name of a male deer — name this springy little word.', 'buck', ARRAY['buck', 'a buck', 'bucks']::text[], 1, 'Buck — the deer never sees a cent of it.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'It''s the dark half of the day, and it sounds exactly like a sword-carrying medieval soldier — name this homophone.', 'night', ARRAY['night', 'knight', 'nite']::text[], 1, 'Night — or knight. Same sound, one wears armor.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'It has two hands and a face but never claps or smiles — name this ticking household object.', 'a clock', ARRAY['clock', 'a clock', 'the clock']::text[], 1, 'A clock — all the equipment, none of the enthusiasm.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'The more it dries, the wetter it gets — name this absorbent bathroom item.', 'a towel', ARRAY['towel', 'a towel', 'the towel', 'towels']::text[], 1, 'A towel — the hardest-working martyr in the bathroom.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'The more of them you take, the more you leave behind — name these walking traces.', 'footsteps', ARRAY['footsteps', 'foot steps', 'footprints', 'foot prints', 'steps']::text[], 1, 'Footsteps — the only thing you gain by leaving.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'It has a neck but no head, and it holds your drink — name this everyday object.', 'a bottle', ARRAY['bottle', 'a bottle', 'the bottle', 'bottles']::text[], 1, 'A bottle — headless, but it still gets popped.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'In two rhyming words, a wealthy big shot — or simply an overfed tabby — is called this.', 'fat cat', ARRAY['fat cat', 'fatcat', 'a fat cat']::text[], 1, 'Fat cat — purring all the way to the bank.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'It can come before ball, path, and print — name this body-part word.', 'foot', ARRAY['foot', 'the foot', 'feet']::text[], 1, 'Foot — carrying the whole language one step at a time.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'It''s the middle of the day, and it reads the same forwards and backwards — name this palindromic hour.', 'noon', ARRAY['noon', '12 noon', 'twelve noon']::text[], 2, 'Noon — the hour that can''t tell if it''s coming or going.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'It can come before light, shine, and walk — name this glowing night word.', 'moon', ARRAY['moon', 'the moon']::text[], 2, 'Moon — lighting the sky and Michael Jackson''s footwork.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'It means completely uncovered, and it sounds exactly like a big furry forest animal — name this homophone.', 'bare', ARRAY['bare', 'bear', 'bair']::text[], 2, 'Bare — or bear. One needs clothes, the other has fur.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'You have two on your head, and corn grows a whole crop of them — name this listening word.', 'ear', ARRAY['ear', 'ears', 'an ear']::text[], 2, 'Ear — the corn hears everything.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'It''s a student at school and the black center of your eye — name this watchful word.', 'pupil', ARRAY['pupil', 'a pupil', 'pupils', 'puple']::text[], 2, 'Pupil — both kinds do their best work when focused.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'A group of crows goes by this delightfully sinister collective name.', 'a murder', ARRAY['murder', 'a murder', 'murder of crows', 'a murder of crows']::text[], 2, 'A murder — crows earned the most dramatic noun in English.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'It means two of a kind, and it sounds exactly like a sweet green fruit — name this homophone.', 'pair', ARRAY['pair', 'pear', 'pare', 'a pair']::text[], 2, 'Pair — or pear. Either way you scored.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'It can follow surf, key, and card — name this flat word.', 'board', ARRAY['board', 'a board', 'bored']::text[], 2, 'Board — flat, dependable, everywhere.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'Racecar and madam both read exactly the same in reverse — words like that are called this.', 'palindromes', ARRAY['palindrome', 'palindromes', 'a palindrome', 'palin drome', 'palindrom']::text[], 2, 'Palindromes — words that moonwalk.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'It''s a metal coil, a season, and a way to jump — name this bouncy triple-duty word.', 'spring', ARRAY['spring', 'a spring', 'the spring']::text[], 2, 'Spring — three jobs, one very energetic word.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'It sits in the middle of your face, and it sounds exactly like being certain of something — name this sniffing homophone.', 'nose', ARRAY['nose', 'knows', 'noze']::text[], 2, 'Nose — it knows. It always knows.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'It can come before cake, board, and holder — name this drinkable word.', 'cup', ARRAY['cup', 'a cup', 'the cup']::text[], 2, 'Cup — dessert, furniture, and car interiors, all covered.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'It has a single eye but cannot see a thing — name this sharp sewing item.', 'a needle', ARRAY['needle', 'a needle', 'the needle', 'needles']::text[], 2, 'A needle — one eye, zero vision, perfect aim.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'No matter how hard you wish, it only ever goes up and never comes down — name this birthday number.', 'your age', ARRAY['age', 'your age', 'my age', 'our age']::text[], 2, 'Your age — the only score nobody wants to run up.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'It stands tall when it''s young and short when it''s old — name this waxy glowing object.', 'a candle', ARRAY['candle', 'a candle', 'the candle', 'candles']::text[], 2, 'A candle — it spends its whole life melting for you.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'The word alphabet is built from these first two Greek letters.', 'alpha and beta', ARRAY['alpha and beta', 'alpha beta', 'alpha, beta', 'alfa and beta']::text[], 2, 'Alpha and beta — the alphabet named itself after its own front row.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'You can catch it but you can never throw it — name this sniffly thing.', 'a cold', ARRAY['cold', 'a cold', 'the cold']::text[], 2, 'A cold — the worst game of catch ever invented.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'It''s a rare verb meaning both to split apart and to cling together — name this two-faced word.', 'cleave', ARRAY['cleave', 'cleve', 'to cleave']::text[], 3, 'Cleave — the word that can''t make up its mind.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'Buzz, hiss, and pop all sound like exactly what they mean — words like that are called this mouthful of a term.', 'onomatopoeia', ARRAY['onomatopoeia', 'onomatopeia', 'onomonopia', 'onomatopia']::text[], 3, 'Onomatopoeia — a word that''s harder to say than to demonstrate.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'A group of owls goes by this very governmental collective name.', 'a parliament', ARRAY['parliament', 'a parliament', 'parliment', 'a parliment']::text[], 3, 'A parliament — the wisest legislature in the forest.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'In the famous typing-practice sentence, the quick brown animal jumping over the lazy dog is this.', 'fox', ARRAY['fox', 'a fox', 'the fox']::text[], 3, 'The fox — jumping that dog since eighteen eighty-five.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'Peter Piper picked a peck — repeating the same starting sound is this poetic device.', 'alliteration', ARRAY['alliteration', 'aliteration', 'a literation']::text[], 3, 'Alliteration — Peter Piper''s only real talent.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'Fittingly, a group of these toothy ocean predators is called a shiver.', 'sharks', ARRAY['sharks', 'shark', 'the sharks']::text[], 3, 'Sharks — a shiver. Whoever named it understood.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'The word salary traces back to Roman soldiers'' allowance for this basic seasoning.', 'salt', ARRAY['salt', 'the salt']::text[], 3, 'Salt — get paid, stay seasoned.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'The curly symbol that stands in for the word and is called this.', 'ampersand', ARRAY['ampersand', 'an ampersand', 'amper sand', 'ampersan']::text[], 3, 'The ampersand — the fanciest shortcut in punctuation.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'Quarantine comes from the Italian for the number of isolation days Venice once demanded of ships — this many.', 'forty', ARRAY['40', 'forty', 'fourty', 'forty days']::text[], 3, 'Forty — Venice invented the lockdown and gave it a name.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'The word muscle comes from the Latin for a little one of these animals.', 'mouse', ARRAY['mouse', 'a mouse', 'mice', 'a little mouse']::text[], 3, 'A mouse — the Romans thought your biceps looked like one moving under the skin.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('wordplay', 'The trailing-off dot dot dot at the end of a sentence is called this.', 'ellipsis', ARRAY['ellipsis', 'an ellipsis', 'elipsis', 'ellipses']::text[], 3, 'An ellipsis — punctuation''s dramatic pause...', false, 'curated_v2');
-- GENERAL / lifestyle (40)
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'It''s the flaky, crescent-shaped star of every French bakery — name this buttery pastry.', 'croissant', ARRAY['croissant', 'croissants', 'a croissant', 'crossant', 'kwason']::text[], 1, 'Croissant — ninety percent butter, ten percent apology.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Three goals by one player in a single soccer match is called this magician-sounding feat.', 'hat trick', ARRAY['hat trick', 'hattrick', 'hat-trick', 'a hat trick']::text[], 1, 'A hat trick — no rabbit required.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Guacamole starts with mashing this creamy green-fleshed fruit.', 'avocado', ARRAY['avocado', 'avocados', 'an avocado', 'avacado']::text[], 1, 'Avocado — ripe for exactly eleven minutes, and you missed it.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Billions of people start their morning with this brewed roasted-bean drink.', 'coffee', ARRAY['coffee', 'a coffee', 'coffe']::text[], 1, 'Coffee — the planet''s legal morning dependency.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Wimbledon''s strawberries, grass courts, and all-white outfits belong to this racket sport.', 'tennis', ARRAY['tennis', 'tenis']::text[], 1, 'Tennis — the only sport with a dress code and a dessert.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Sushi, sashimi, and tempura all come from this island country.', 'Japan', ARRAY['japan']::text[], 1, 'Japan — raw fish, perfected.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Every Olympics opens with a months-long global relay of this burning object.', 'the torch', ARRAY['torch', 'the torch', 'olympic torch', 'the olympic torch', 'flame', 'the flame', 'the olympic flame']::text[], 1, 'The torch — the world''s longest game of pass-the-candle.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Spaghetti, penne, and fusilli are all shapes of this boiled Italian staple.', 'pasta', ARRAY['pasta', 'noodles', 'pastas']::text[], 1, 'Pasta — same dough, six hundred outfits.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'A vegetarian diet cuts out this entire food group.', 'meat', ARRAY['meat', 'meats']::text[], 1, 'Meat — the one thing not on the menu.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'The Tour de France is a grueling three-week race for these vehicles.', 'bicycles', ARRAY['bicycles', 'bikes', 'bicycle', 'bike', 'cycles', 'a bicycle']::text[], 1, 'Bicycles — three weeks, one very sore peloton.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'On Halloween, grinning faces get carved into this big orange gourd.', 'pumpkin', ARRAY['pumpkin', 'a pumpkin', 'pumpkins', 'punkin']::text[], 1, 'Pumpkin — the only vegetable with a career in show business.', false, 'curated_v2');
-- closest-number
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Closest guess wins — to one decimal place, the number of miles in a full marathon.', '26.2', ARRAY['26.2', 'twenty six point two', 'twenty-six point two']::text[], 2, 'Twenty-six point two — and that point two is where the crying happens.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'In tennis, a score of zero goes by this romantic name.', 'love', ARRAY['love', 'luv']::text[], 2, 'Love — tennis is the only place it means you have nothing.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Paella, the famous seasoned rice dish, comes from this Mediterranean country.', 'Spain', ARRAY['spain', 'espana']::text[], 2, 'Spain — Valencia would like a word with everyone who adds chorizo.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Winning the Masters earns a golfer this famously colored jacket.', 'green jacket', ARRAY['green', 'green jacket', 'a green jacket', 'the green jacket']::text[], 2, 'The green jacket — ugly color, priceless tailoring.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Cheddar cheese takes its name from a village in this country.', 'England', ARRAY['england', 'the uk', 'uk', 'united kingdom', 'britain', 'great britain']::text[], 2, 'England — Cheddar is a real place, with a real gorge, and really good cheese.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Japan''s traditional rice wine goes by this short name.', 'sake', ARRAY['sake', 'saki', 'sah kay', 'sockey']::text[], 2, 'Sake — rice, but make it a toast.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'A baker''s dozen contains exactly this many items.', '13', ARRAY['13', 'thirteen', 'a baker''s dozen is thirteen']::text[], 2, 'Thirteen — one extra, so the baker stayed out of jail.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'In chess, the only piece that moves exclusively on diagonals is this clerical one.', 'bishop', ARRAY['bishop', 'the bishop', 'a bishop', 'bishops']::text[], 2, 'The bishop — a lifetime of sidestepping.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Michael Jordan won six championships with this horned Chicago team.', 'the Bulls', ARRAY['bulls', 'the bulls', 'chicago bulls', 'the chicago bulls']::text[], 2, 'The Bulls — six rings and one very famous tongue.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Goulash, the paprika-loving stew, is the national dish of this central European country.', 'Hungary', ARRAY['hungary', 'hungry', 'hungery']::text[], 2, 'Hungary — yes, the country name and the appetite joke write themselves.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Before any stoppage time, a regulation soccer match runs this many minutes.', '90', ARRAY['90', 'ninety', 'ninety minutes']::text[], 2, 'Ninety — plus however long the referee is feeling dramatic.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Named for the color of Capuchin friars'' robes, espresso plus foamed milk makes this Italian coffee.', 'cappuccino', ARRAY['cappuccino', 'capuccino', 'cappucino', 'a cappuccino']::text[], 2, 'Cappuccino — monk fashion, in a cup.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Boxing matches take place in a squared-off area that''s ironically called this.', 'ring', ARRAY['ring', 'the ring', 'a ring', 'boxing ring', 'a boxing ring']::text[], 2, 'The ring — four corners, zero circles, nobody''s fixed the name.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Feta, olives, and tzatziki anchor the dinner table in this Mediterranean country.', 'Greece', ARRAY['greece', 'grease']::text[], 2, 'Greece — where every meal is a small festival.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'A baseball team puts exactly this many defensive players on the field.', '9', ARRAY['9', 'nine', 'nine players']::text[], 2, 'Nine — one for every position, no substitutes hiding in the outfield.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'On the classic American Monopoly board, the priciest property is this seaside square.', 'Boardwalk', ARRAY['boardwalk', 'board walk', 'the boardwalk']::text[], 2, 'Boardwalk — four hundred dollars, endless family arguments.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'The Scoville scale rates chili peppers on this fiery quality.', 'heat', ARRAY['heat', 'spiciness', 'hotness', 'spice', 'how hot they are', 'spicyness', 'their heat']::text[], 2, 'Heat — measured in units of instant regret.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Hand-picked thread by thread from crocus flowers, the world''s priciest spice by weight is this golden one.', 'saffron', ARRAY['saffron', 'safron', 'safran']::text[], 3, 'Saffron — worth more per gram than a bad decision in Vegas.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Sweet, salty, sour, bitter — the savory fifth taste goes by this Japanese name.', 'umami', ARRAY['umami', 'oomami', 'umame', 'oo mommy']::text[], 3, 'Umami — the taste that makes broth worth writing home about.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'The only Grand Slam tournament played on red clay is this Parisian tennis major.', 'the French Open', ARRAY['french open', 'the french open', 'roland garros', 'roland-garros', 'the french']::text[], 3, 'The French Open — where white outfits go to turn orange.', false, 'curated_v2');
-- closest-number
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Closest guess wins — the total number of squares on a standard chessboard.', '64', ARRAY['64', 'sixty four', 'sixty-four']::text[], 3, 'Sixty-four — eight by eight, no negotiating.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'The name vodka comes from the Slavic word for this humble everyday liquid.', 'water', ARRAY['water', 'little water']::text[], 3, 'Water — vodka literally means little water. The Slavs undersold it.', false, 'curated_v2');
-- two-step
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'A cloud-like meringue dessert down under and a legendary Russian ballerina share this graceful name.', 'Pavlova', ARRAY['pavlova', 'pavlover', 'pav lova', 'pav', 'pavlovah']::text[], 3, 'Pavlova — the dancer got a dessert; most of us just get a headstone.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'The fifty-point dot at the dead center of a dartboard is called this.', 'the bullseye', ARRAY['bullseye', 'bulls eye', 'the bullseye', 'bull', 'the bull', 'inner bull']::text[], 3, 'The bullseye — fifty points, and everyone at the pub saw it.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'In cricket, one over consists of exactly this many legal deliveries.', 'six', ARRAY['6', 'six', 'six balls']::text[], 3, 'Six — then everyone swaps ends and pretends that''s normal.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Its name is Italian for pick-me-up — name this coffee-soaked layered dessert.', 'tiramisu', ARRAY['tiramisu', 'tira misu', 'teramisu', 'tiramisoo']::text[], 3, 'Tiramisu — dessert and espresso shot, one spoon.', false, 'curated_v2');
-- closest-number
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Closest guess wins — in feet, the length of a tenpin bowling lane from the foul line to the head pin.', '60', ARRAY['60', 'sixty', 'sixty feet']::text[], 3, 'Sixty feet — of polished wood between you and glory.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Chefs call having every ingredient prepped and in position before cooking by this French term.', 'mise en place', ARRAY['mise en place', 'mise-en-place', 'meez on plass', 'mees en plas', 'miz en plas']::text[], 3, 'Mise en place — French for everything where it should be, which is why your kitchen isn''t French.', false, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('lifestyle', 'Biltong, the air-dried spiced meat snack, hails from this African country.', 'South Africa', ARRAY['south africa', 'southafrica']::text[], 3, 'South Africa — jerky''s older, tougher cousin.', false, 'curated_v2');
-- ADULT (40) — adult_history / adult_popculture / adult_science / adult_wordplay
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_history', 'Divorced, beheaded, died — England''s much-married Henry the Eighth got through this many wives.', 'six', ARRAY['6', 'six', 'six wives']::text[], 1, 'Six — the man treated marriage like a subscription service.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_history', 'From 1920 to 1933, the US Constitution banned making and selling this entire category of drink.', 'alcohol', ARRAY['alcohol', 'booze', 'liquor', 'alcoholic drinks', 'alcoholic beverages', 'spirits']::text[], 1, 'Alcohol — and America immediately invented better parties.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_history', 'Legend says she rode through Coventry wearing nothing but her hair, protesting her husband''s taxes — name this famously unclothed lady.', 'Lady Godiva', ARRAY['lady godiva', 'godiva', 'lady go diva']::text[], 1, 'Lady Godiva — the original tax protest nobody looked away from. Well, one guy did the opposite.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_history', 'Emperor Caligula reportedly declared war on the sea itself and ordered his troops to collect these as plunder.', 'seashells', ARRAY['seashells', 'shells', 'sea shells']::text[], 2, 'Seashells — Rome''s finest, defeated by the beach.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_history', 'Gin — the ruin of eighteenth-century London — gets its signature piney flavor from these little berries.', 'juniper berries', ARRAY['juniper', 'juniper berries', 'juniperberries', 'junipers']::text[], 2, 'Juniper — one berry, an entire city-wide hangover.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_history', 'The 1904 Olympic marathon winner was dosed mid-race with brandy and this actual rat poison.', 'strychnine', ARRAY['strychnine', 'strick nine', 'strychnine poison', 'stricknine']::text[], 2, 'Strychnine — early sports science was just poison and confidence.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_history', 'Renaissance Rome''s most scandalous pope, Alexander the Sixth, belonged to this infamous Spanish-Italian family.', 'the Borgias', ARRAY['borgia', 'the borgias', 'borgias', 'borja', 'the borgia family']::text[], 2, 'The Borgias — the family that put the sin in Vatican.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_history', 'Benjamin Franklin wrote a notorious letter advising young men to take an older one of this scandalous kind of companion.', 'a mistress', ARRAY['mistress', 'a mistress', 'mistresses', 'lover', 'a lover', 'lovers']::text[], 2, 'A mistress — founding father, and apparently founding wingman.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_history', 'Medieval London''s licensed brothels paid their rent to the bishop of this English cathedral city.', 'Winchester', ARRAY['winchester', 'win chester']::text[], 3, 'Winchester — the church collected, and history kept the receipts.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_history', 'Dragging Russia toward modern fashion, Tsar Peter the Great slapped a tax on men who kept these.', 'beards', ARRAY['beards', 'beard', 'a beard', 'their beards']::text[], 3, 'Beards — taxed by the chin. Imagine the audits.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_popculture', 'The 2004 Super Bowl halftime wardrobe malfunction briefly exposed this pop superstar.', 'Janet Jackson', ARRAY['janet jackson', 'janet']::text[], 1, 'Janet Jackson — half a second that invented the broadcast delay.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_popculture', 'Sex and the City''s cosmo-sipping newspaper columnist is this Manhattan heroine.', 'Carrie Bradshaw', ARRAY['carrie bradshaw', 'carrie', 'carry bradshaw', 'kerry bradshaw']::text[], 1, 'Carrie Bradshaw — one column a week, a closet worth a mortgage.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_popculture', 'Unemployed Sheffield steelworkers strip for one unforgettable night in this 1997 British comedy.', 'The Full Monty', ARRAY['the full monty', 'full monty', 'full monte', 'the full monte']::text[], 1, 'The Full Monty — they left the hats on, and nothing else.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_popculture', 'The Rocky Horror Picture Show is ruled by this fishnet-wearing, sweet-transvestite mad scientist.', 'Frank-N-Furter', ARRAY['frank n furter', 'frankenfurter', 'frank-n-furter', 'doctor frank n furter', 'dr frank n furter', 'frank']::text[], 2, 'Frank-N-Furter — science has never had better legs.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_popculture', 'In 1969, John Lennon and Yoko Ono staged their famous week-long peace protest without ever leaving this piece of furniture.', 'a bed', ARRAY['bed', 'a bed', 'the bed', 'their bed']::text[], 2, 'A bed — activism you can do in pajamas. Respect.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_popculture', 'Burt Reynolds'' cheeky 1972 nude centerfold ran in this famous women''s magazine.', 'Cosmopolitan', ARRAY['cosmopolitan', 'cosmo']::text[], 2, 'Cosmopolitan — Burt on a bearskin rug. The seventies were a different planet.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_popculture', 'Basic Instinct''s infamous leg-cross interrogation scene starred this blonde actress.', 'Sharon Stone', ARRAY['sharon stone', 'stone', 'sharon']::text[], 2, 'Sharon Stone — one scene, one million pause buttons.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_popculture', 'Scandalized 1950s television gave hip-swiveling Elvis this rhyming anatomical nickname.', 'Elvis the Pelvis', ARRAY['elvis the pelvis', 'the pelvis', 'pelvis']::text[], 2, 'Elvis the Pelvis — they filmed him from the waist up. It did not help.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_popculture', 'Serge Gainsbourg''s heavy-breathing 1969 duet, denounced by the Vatican, featured this English actress.', 'Jane Birkin', ARRAY['jane birkin', 'birkin', 'jane burkin']::text[], 3, 'Jane Birkin — banned by the Vatican, number one everywhere else.', true, 'curated_v2');
-- two-step
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_popculture', 'Watergate''s secret informant Mark Felt took his press codename from the title of a notorious 1972 adult film — name this codename.', 'Deep Throat', ARRAY['deep throat', 'deepthroat']::text[], 3, 'Deep Throat — the only adult film credited with toppling a president.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_science', 'Cuddling, kissing, and general canoodling flood your brain with this so-called love hormone.', 'oxytocin', ARRAY['oxytocin', 'oxy tocin', 'oxytosin', 'oxitocin']::text[], 1, 'Oxytocin — your brain''s in-house matchmaker.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_science', 'In this curly-tailed little fish species, it''s the males who get pregnant and give birth.', 'seahorse', ARRAY['seahorse', 'seahorses', 'sea horse', 'sea horses', 'the seahorse']::text[], 1, 'The seahorse — dads doing literally all the labor.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_science', 'Every drink you''ve ever had gets processed on its way out by this hardworking detox organ.', 'the liver', ARRAY['liver', 'the liver', 'your liver']::text[], 1, 'The liver — it forgives, but it keeps a ledger.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_science', 'A male honeybee drone dies immediately after doing this just once.', 'mating', ARRAY['mating', 'sex', 'having sex', 'reproducing', 'mating with the queen', 'breeding']::text[], 2, 'Mating — one glorious flight, then lights out. Nature is brutal on the boys.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_science', 'Unique among human organs, the clitoris exists purely for this happy purpose.', 'pleasure', ARRAY['pleasure', 'sexual pleasure', 'fun', 'for pleasure']::text[], 2, 'Pleasure — the only organ with exactly one job, and what a job.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_science', 'Oysters owe their aphrodisiac reputation partly to sky-high levels of this mineral.', 'zinc', ARRAY['zinc', 'zink']::text[], 2, 'Zinc — romance, apparently, is a trace mineral.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_science', 'Famously, the female of this elegant garden insect sometimes eats her mate mid-romance.', 'praying mantis', ARRAY['praying mantis', 'mantis', 'preying mantis', 'a praying mantis']::text[], 2, 'The praying mantis — dinner and a date, in the wrong order.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_science', 'In the American system, a hundred-proof whiskey contains exactly this percentage of alcohol.', '50', ARRAY['50', 'fifty', 'fifty percent', '50 percent', 'half']::text[], 3, 'Fifty percent — proof is just alcohol doing math at double volume.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_science', 'Relative to body size, the most generously endowed creature in the animal kingdom is this humble shore-clinging crustacean.', 'barnacle', ARRAY['barnacle', 'barnacles', 'the barnacle', 'a barnacle']::text[], 3, 'The barnacle — glued to a rock, and still the champion.', true, 'curated_v2');
-- closest-number
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_science', 'Closest guess wins — the number of little crimps around the edge of a standard beer bottle cap.', '21', ARRAY['21', 'twenty one', 'twenty-one']::text[], 3, 'Twenty-one — count them next round. You know you will.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_wordplay', 'Get your minds out of the gutter — it''s long, hard, and full of seamen — name this underwater vessel.', 'submarine', ARRAY['submarine', 'a submarine', 'sub', 'a sub']::text[], 1, 'A submarine — you all hesitated, and that says plenty.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_wordplay', 'It goes in hard and dry and comes out soft and sticky — name this minty chewable.', 'chewing gum', ARRAY['gum', 'chewing gum', 'bubble gum', 'bubblegum', 'a gum']::text[], 1, 'Chewing gum — whatever you were thinking, keep it to yourself.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_wordplay', 'Millions of adults grab it, turn it on, and play with it in bed every single night — name this glowing device.', 'phone', ARRAY['phone', 'a phone', 'cell phone', 'cellphone', 'mobile phone', 'smartphone', 'mobile', 'my phone', 'the phone']::text[], 2, 'Your phone — the longest relationship at this table.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_wordplay', 'Avocado comes from an Aztec word that also, charmingly, named this dangling body part.', 'testicle', ARRAY['testicle', 'testicles', 'balls', 'a testicle', 'the testicle']::text[], 2, 'Testicle — enjoy your toast tomorrow morning.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_wordplay', 'The word for taking pleasure in cruelty comes from the name of this scandalous French marquis.', 'the Marquis de Sade', ARRAY['sade', 'marquis de sade', 'de sade', 'the marquis de sade', 'marquee de sade']::text[], 2, 'The Marquis de Sade — so infamous they made him a dictionary entry.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_wordplay', 'A growler, in bar parlance, is a big jug you carry home filled with this.', 'beer', ARRAY['beer', 'draft beer', 'craft beer', 'ale']::text[], 2, 'Beer — the growler growls because it''s half empty already.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_wordplay', 'French politely calls the moment of climax la petite mort — translated into English as this morbid little phrase.', 'the little death', ARRAY['the little death', 'little death', 'a little death', 'small death']::text[], 3, 'The little death — leave it to the French to make it sound like poetry.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_wordplay', 'The drink punch takes its name from the Hindi word for its traditional number of ingredients — this many.', 'five', ARRAY['5', 'five']::text[], 3, 'Five — spirit, sugar, lemon, water, spice. The original recipe app.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_wordplay', 'A merkin is a centuries-old wig designed for this unexpected region of the body.', 'the pubic area', ARRAY['pubic area', 'the pubic area', 'pubic hair', 'pubes', 'groin', 'the groin', 'down there', 'crotch', 'the crotch']::text[], 3, 'The pubic area — history''s most specialized hairpiece.', true, 'curated_v2');
INSERT INTO lily_questions (category, question, canonical_answer, acceptable_answers, difficulty_tier, reveal_color, adult, source) VALUES ('adult_wordplay', 'Sailors nicknamed their daily Royal Navy ration Nelson''s blood — the drink itself is this.', 'rum', ARRAY['rum', 'rhum', 'dark rum']::text[], 3, 'Rum — the navy ran on it until nineteen seventy. Look it up, then pour one.', true, 'curated_v2');
